fix(kvm): kvm screens refresh between multiple tabs
open-amt-cloud-toolkit/ui-toolkit pull request #49
Opened 2021-02-03 09:09 UTC by Mahendra-intel

2021-02-04 03:46 UTC, madhavilosetty-intel approved these changes

2021-02-04 16:11 UTC, rsdmike requested changes

2021-02-04 16:11 UTC, rsdmike commented on src/reactjs/components/AuditLog/index.tsx
> +// library.add(faInfoCircle, faAngleDoubleRight, faAngleDoubleLeft, faAngleRight, faAngleLeft, faFileExport);
remove commented code

2021-02-05 06:02 UTC, Mahendra-intel commented on src/reactjs/components/AuditLog/index.tsx
> +// library.add(faInfoCircle, faAngleDoubleRight, faAngleDoubleLeft, faAngleRight, faAngleLeft, faFileExport);
done

2021-02-24 03:01 UTC, madhavilosetty-intel approved these changes

2021-02-25 15:56 UTC, rsdmike approved these changes

2021-02-25 15:56 UTC, merged