feat: added IDER support
open-amt-cloud-toolkit/ui-toolkit pull request #781
Opened 2023-10-27 15:41 UTC by madhavilosetty-intel

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2023-11-03 18:42 UTC, rsdmike requested changes

2023-11-03 18:42 UTC, rsdmike commented on src/core/AMTIDER.ts
> +import { TypeConverter } from './Converter'
missing copyright headers on new files

2023-11-03 18:42 UTC, rsdmike commented on src/core/AMTIDER.ts
> +    console.log('cmdid :', cmdid, 'data', typeof (data), 'completed :', completed, 'dma :', dma)
need to remove all debug statements

2023-11-09 04:04 UTC, madhavilosetty-intel commented on src/core/AMTIDER.ts
> +import { TypeConverter } from './Converter'
added

2023-11-09 04:05 UTC, madhavilosetty-intel commented on src/core/AMTIDER.ts
> +    console.log('cmdid :', cmdid, 'data', typeof (data), 'completed :', completed, 'dma :', dma)
updated

2023-11-09 22:01 UTC, rsdmike approved these changes

2023-11-09 22:08 UTC, merged